### PR TITLE
support for phone field in report

### PR DESCRIPTION
**Pull request by yashodha**
add phone fields to the birthday report
birthday

### CODE REVIEW

**Comment by yashodha** [comment]
@bjendres This is an improvement. Can you please merge this?

**Comment by bjendres** [comment]
sure, looks good, thanks. 

I'm currently on holiday, but let me/us know if you need a release.

**Comment by yashodha** [comment]
@bjendres It would be great if you could push a release. Thanks!

**Comment by yashodha** [comment]
@bjendres and please let me know when you do. Thanks!

**Comment by yashodha** [comment]
@bjendres Would you be pushing a new release on this extension?

**Pull request merged**
